### ISSUE TITLE
If user didn't to use "sudo", it will fail.

### ISSUE THREAD

**Issue by alleen** [BlueCatMe/GoogleDriveUploader#1]
If user didn't to use "sudo", it will show error msg and fail.

Traceback (most recent call last):
  File "smaug.py", line 101, in <module>
    main(sys.argv)
  File "smaug.py", line 88, in main
    if not action_exec.authorize(options):
  File "/home/alleen/data-disk/Workspace/Smaug/ActionBase.py", line 69, in authorize
    if service.authorize():
  File "/home/alleen/data-disk/Workspace/Smaug/GoogleDriveService.py", line 176, in authorize
    return self.service_refresh()
  File "/home/alleen/data-disk/Workspace/Smaug/GoogleDriveService.py", line 170, in service_refresh
    result = self.authorize_raw()
  File "/home/alleen/data-disk/Workspace/Smaug/GoogleDriveService.py", line 124, in authorize_raw
    credentials = flow.step2_exchange(code)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client-1.4.11-py2.7.egg/oauth2client/util.py", line 137, in positional_wrapper
  File "/usr/local/lib/python2.7/dist-packages/oauth2client-1.4.11-py2.7.egg/oauth2client/client.py", line 1982, in step2_exchange
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/**init**.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/**init**.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 241, in __init__
    ciphers)
ssl.SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

**Comment by BlueCatMe** [comment]
Hi Alleen,

please try this:

import certifi
print certifi.where()

**Comment by alleen** [comment]
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import cerifi
ImportError: No module named cerifi
